project_id = "ngcyfbstajfcfdhlelbz"

[functions.test-openai-key]
verify_jwt = false

[functions.openai-chat]
verify_jwt = false

[functions.openai-embedding]
verify_jwt = false

[functions.openai-safety]
verify_jwt = false

[functions.evai-autolearn-scan]
verify_jwt = false

[functions.evai-orchestrate]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false
